# Generated by Django 3.1.7 on 2023-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingAppointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingappointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
