# Generated by Django 3.1.7 on 2023-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingAppointments', '0003_auto_20230414_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingappointment',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
