# Generated by Django 3.1.7 on 2023-02-12 08:50

import bikeRental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rent_duration_and_price', bikeRental.models.RentPriceField(default={})),
            ],
        ),
    ]
