# Generated by Django 3.1.7 on 2023-02-12 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikeRental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalproduct',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='color',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='grouping',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='person_username',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='rented_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='size',
            field=models.CharField(default='L', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='slug',
            field=models.SlugField(default='first-rented-bike'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
