# Generated by Django 3.1.7 on 2023-02-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeRental', '0002_auto_20230212_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproduct',
            name='map_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
