# Generated by Django 3.1.7 on 2023-02-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeRental', '0003_rentalproduct_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproduct',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
