# Generated by Django 3.1.7 on 2023-02-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeRental', '0004_rentalproduct_is_rented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproduct',
            name='rented_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalproduct',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
