# Generated by Django 3.1.7 on 2023-02-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeRental', '0005_auto_20230212_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproduct',
            name='person_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
