# Generated by Django 3.1.7 on 2023-02-21 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bikeRental', '0006_auto_20230212_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalproduct',
            name='person_username',
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
