# Generated by Django 3.1.7 on 2023-02-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeRental', '0007_auto_20230221_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproduct',
            name='renter_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
