# Generated by Django 3.1.7 on 2023-02-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeRental', '0010_rentalproduct_stripe_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproduct',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentalproduct',
            name='map_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentalproduct',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
