# Generated by Django 3.1.7 on 2023-02-21 20:24

import bikeRental.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeRental', '0011_auto_20230221_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproduct',
            name='rent_duration_and_price',
            field=bikeRental.models.RentPriceField(default={}, null=True),
        ),
    ]
