# Generated by Django 3.1.7 on 2023-02-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userBikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usedbike',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='usedbike',
            name='date_added',
        ),
    ]
