# Generated by Django 3.1.7 on 2023-02-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBikes', '0002_auto_20230226_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedbike',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
