# Generated by Django 3.1.7 on 2023-04-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclingEvent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_and_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
